#!/usr/bin/env bash
#
# Finishes the Cloudflare Tunnel cutover for coreprop.me.
#
# Run this AFTER two things you have to do by hand:
#
#   1. coreprop.me is added to Cloudflare (free plan) and Namecheap's
#      "Custom DNS" is set to the two nameservers Cloudflare gave you.
#      Check it landed:  dig +short coreprop.me NS   -> *.ns.cloudflare.com
#
#   2. cloudflared tunnel login
#      (opens a browser; pick coreprop.me — this writes ~/.cloudflared/cert.pem)
#
# Then:  bash deploy/selfhost/finish-tunnel-setup.sh
#
# Safe to re-run: every step checks for existing state first.
set -euo pipefail

DOMAIN="coreprop.me"
TUNNEL="coreprop"
PORT="8010"
CFDIR="$HOME/.cloudflared"
PLIST="$HOME/Library/LaunchAgents/com.coreprop.server.plist"

say()  { printf '\n\033[1m==> %s\033[0m\n' "$*"; }
fail() { printf '\n\033[31mERROR: %s\033[0m\n' "$*" >&2; exit 1; }

# --- preconditions --------------------------------------------------------

say "Checking preconditions"

command -v cloudflared >/dev/null || fail "cloudflared not installed (brew install cloudflared)"

# Not a hard failure: the tunnel can be created, configured and routed while
# the zone is still pending. Only the final HTTPS verification needs the
# delegation to have landed, so warn and keep going.
if dig +short "$DOMAIN" NS | grep -qi cloudflare; then
  echo "  nameservers ....... on Cloudflare"
  NS_READY=1
else
  printf '\033[33m  nameservers ....... NOT on Cloudflare yet (%s)\033[0m\n' \
    "$(dig +short "$DOMAIN" NS | tr '\n' ' ')"
  echo "                      Everything below still works; the site just will"
  echo "                      not resolve publicly until delegation lands."
  NS_READY=0
fi

[ -f "$CFDIR/cert.pem" ] || fail "no $CFDIR/cert.pem — run: cloudflared tunnel login"
echo "  cloudflared login . ok"

curl -fsS --max-time 5 "http://127.0.0.1:$PORT/health" >/dev/null \
  || fail "app not answering on 127.0.0.1:$PORT — is the launchd service loaded?
  launchctl load $PLIST"
echo "  app on :$PORT ..... ok"

grep -q "https://$DOMAIN" "$PLIST" \
  || fail "PUBLIC_BASE_URL in $PLIST is not https://$DOMAIN"
echo "  PUBLIC_BASE_URL ... https://$DOMAIN"

# --- tunnel ---------------------------------------------------------------

say "Creating tunnel '$TUNNEL'"
if cloudflared tunnel list 2>/dev/null | awk '{print $2}' | grep -qx "$TUNNEL"; then
  echo "  already exists — reusing"
else
  cloudflared tunnel create "$TUNNEL"
fi

UUID="$(cloudflared tunnel list 2>/dev/null | awk -v n="$TUNNEL" '$2==n {print $1}' | head -1)"
[ -n "$UUID" ] || fail "could not determine the tunnel UUID"
CREDS="$CFDIR/$UUID.json"
[ -f "$CREDS" ] || fail "credentials file missing: $CREDS"
echo "  uuid .............. $UUID"

# --- config ---------------------------------------------------------------

say "Writing $CFDIR/config.yml"
if [ -f "$CFDIR/config.yml" ]; then
  cp "$CFDIR/config.yml" "$CFDIR/config.yml.bak.$(date +%s)"
  echo "  backed up the existing config"
fi

cat > "$CFDIR/config.yml" <<YAML
# Generated by deploy/selfhost/finish-tunnel-setup.sh
tunnel: $UUID
credentials-file: $CREDS

originRequest:
  connectTimeout: 30s
  noTLSVerify: false

ingress:
  # Must match PUBLIC_BASE_URL in com.coreprop.server.plist exactly.
  - hostname: $DOMAIN
    service: http://127.0.0.1:$PORT
  - hostname: www.$DOMAIN
    service: http://127.0.0.1:$PORT
  # cloudflared refuses to start without a final hostname-less rule.
  - service: http_status:404
YAML
cloudflared tunnel ingress validate
echo "  config valid"

# --- dns ------------------------------------------------------------------

say "Routing DNS"
for host in "$DOMAIN" "www.$DOMAIN"; do
  if cloudflared tunnel route dns "$TUNNEL" "$host" 2>&1 | tee /tmp/cfroute.$$ | grep -qiE "error|failed"; then
    if grep -qi "already exists" /tmp/cfroute.$$; then
      echo "  $host ... record already points here"
    else
      rm -f /tmp/cfroute.$$; fail "could not route $host (see output above)"
    fi
  else
    echo "  $host ... routed"
  fi
  rm -f /tmp/cfroute.$$
done

# --- run it ---------------------------------------------------------------

say "Starting cloudflared as a service"
# NOT `brew services start cloudflared`. Homebrew's bundled plist runs
# `cloudflared tunnel --url http://127.0.0.1:8010`, a QUICK tunnel: it ignores
# ~/.cloudflared/config.yml and the named tunnel entirely, mints a fresh random
# *.trycloudflare.com hostname on every restart, and reports `error` in
# `brew services list`. coreprop.me would never be served. Verified the hard
# way on 2026-08-11.
if brew services list 2>/dev/null | grep -q '^cloudflared'; then
  echo "  stopping homebrew's quick-tunnel service first"
  brew services stop cloudflared >/dev/null 2>&1 || true
  pkill -f 'cloudflared tunnel --url' 2>/dev/null || true
fi

mkdir -p "$HOME/Library/Logs/coreprop"
cp "$(dirname "$0")/com.coreprop.tunnel.plist" "$HOME/Library/LaunchAgents/"
launchctl unload "$HOME/Library/LaunchAgents/com.coreprop.tunnel.plist" 2>/dev/null || true
launchctl load "$HOME/Library/LaunchAgents/com.coreprop.tunnel.plist"

printf '  waiting for the tunnel to come up'
for _ in $(seq 1 30); do
  if curl -fsS --max-time 5 "https://$DOMAIN/health" >/dev/null 2>&1; then
    printf ' up\n'; break
  fi
  printf '.'; sleep 3
done
echo

# --- verify ---------------------------------------------------------------

say "Verifying"
echo "  tunnel connectors:"
cloudflared tunnel info "$TUNNEL" 2>/dev/null | tail -3 | sed 's/^/    /'

if [ "$NS_READY" = "0" ]; then
  cat <<PENDING

  Skipping the HTTPS check — the zone is still pending at Cloudflare, so its
  nameservers do not serve records yet and $DOMAIN cannot resolve for anyone.
  Nothing is wrong with the tunnel; watch for it to go live with:

    watch -n 60 'dig +short coreprop.me NS'

  Then re-run this script for the full verification.
PENDING
  exit 0
fi

HEALTH="$(curl -fsS --max-time 15 "https://$DOMAIN/health" 2>/dev/null || true)"
[ -n "$HEALTH" ] || fail "https://$DOMAIN/health did not answer.
  launchctl list | grep coreprop        # both server and tunnel loaded?
  cloudflared tunnel info $TUNNEL
  tail -f ~/Library/Logs/coreprop/tunnel.err.log"

echo "  /health ........... $HEALTH"
echo "  /api/status ....... $(curl -fsS --max-time 20 "https://$DOMAIN/api/status" | head -c 120)"
echo "  /api/billing/config $(curl -fsS --max-time 15 "https://$DOMAIN/api/billing/config" | head -c 90)"

say "Done — https://$DOMAIN is live"
cat <<NEXT

Remaining, in order:

  1. Confirm the paywall is closed (must be "enabled":true above).

  2. Supabase -> Authentication -> URL Configuration:
     add https://$DOMAIN to the redirect allowlist, or logins bounce.

  3. Stripe -> your webhook endpoint -> "Send test webhook".
     Pick customer.subscription.created. Expect HTTP 200.
     Watch it land:  tail -f ~/Library/Logs/coreprop/server.log

  4. Stop the Mac sleeping (needs your password — a sleeping host is a
     dead site):
       sudo pmset -a sleep 0 && sudo pmset -a autorestart 1

  5. Roll the Stripe secret key (it was pasted into a chat transcript),
     put the new sk_live_ in .env, then:
       launchctl unload $PLIST && launchctl load $PLIST
       python3 deploy/selfhost/verify-webhook.py
NEXT
