#!/usr/bin/env python3
"""
Regenerate the stat_type -> card-label alias map used by the browser extension.

PrizePicks' projections carry BOTH names:
  stat_type          e.g. "Pitcher Strikeouts"   <- what CoreProp stores on a leg
  stat_display_name  e.g. "Ks"                   <- what the board actually prints

The card renders `stat_display_name || stat_type.name` (PP bundle module 70031),
so an extension matching a leg against the visible label needs the mapping or it
silently skips every abbreviated prop.

Run this whenever PP adds markets; paste the output into STAT_ALIASES in
coreprop-extension/pp-dom.js.

    python3 tests/extension/regen-stat-aliases.py
"""
import collections
import json
import subprocess
import sys

URL = "https://partner-api.prizepicks.com/projections?per_page=250"
UA = ("Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 "
      "(KHTML, like Gecko) Chrome/131.0 Safari/537.36")


def fetch(url: str) -> dict:
    """Fetch via curl rather than urllib.

    Deliberate: several dev machines here have an incomplete CA bundle for
    Python (the same failure the scraper tests log), while curl uses the system
    keychain and works. Optional local path argument lets you re-run offline
    against a saved response.
    """
    if len(sys.argv) > 1:
        with open(sys.argv[1]) as fh:
            return json.load(fh)
    out = subprocess.run(
        ["curl", "-sS", "--max-time", "90", "-H", "Accept: application/json",
         "-A", UA, url],
        capture_output=True, text=True, check=True,
    ).stdout
    return json.loads(out)


def canon(s: str) -> str:
    """Mirror canonStat() in pp-dom.js exactly."""
    return "".join(ch for ch in (s or "").lower() if ch.isalnum())


def main() -> int:
    payload = fetch(URL)

    pairs = collections.defaultdict(set)
    for p in payload.get("data", []):
        a = p.get("attributes", {})
        st, sd = a.get("stat_type") or "", a.get("stat_display_name") or ""
        if st and sd:
            pairs[st].add(sd)

    # Only entries where the printed label differs from the API name need an alias.
    diff = {k: sorted(v) for k, v in pairs.items()
            if any(canon(x) != canon(k) for x in v)}

    print(f"// Generated by tests/extension/regen-stat-aliases.py from "
          f"{len(payload.get('data', []))} live projections.")
    print(f"// {len(pairs)} stat types seen, {len(diff)} whose card label differs.")
    print("const STAT_ALIASES = {")
    for k in sorted(diff):
        vals = ", ".join(f"'{canon(v)}'" for v in diff[k] if canon(v) != canon(k))
        # Always quote: canonicalised keys like "3ptmade" are not valid JS identifiers.
        key = f"'{canon(k)}':"
        print(f"  {key:<26} [{vals}],   // {k} -> {'/'.join(diff[k])}")
    print("};")
    return 0


if __name__ == "__main__":
    sys.exit(main())
